### 7장 텍스트 데이터 다루기

In [14]:
sentences = ['가장 자연스럽고 좋은 ~좋은 영화 였다', '최고의 영화 4편이 기대됨']

In [15]:
type(sentences), len(sentences)

(list, 2)

### BOW(Bag of words) 단어 가방으로 전처리

In [16]:
#420 
from sklearn.feature_extraction.text import CountVectorizer # 갯수를 세어서 배열로 만든다.

In [17]:
vect = CountVectorizer()

In [18]:
vect.fit(sentences)

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), preprocessor=None, stop_words=None,
        strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
        tokenizer=None, vocabulary=None)

In [19]:
len(vect.vocabulary_), vect.vocabulary_ # 등장하는 어휘들

(8,
 {'가장': 1,
  '자연스럽고': 5,
  '좋은': 6,
  '영화': 4,
  '였다': 3,
  '최고의': 7,
  '4편이': 0,
  '기대됨': 2})

In [20]:
#dense_matrix <-> sparse_matrix(자연어) : 메모리 절약하기 위해서 사용
sparse_matrix = vect.transform(sentences) # 자연어를 BOW로 변환
sparse_matrix

<2x8 sparse matrix of type '<class 'numpy.int64'>'
	with 9 stored elements in Compressed Sparse Row format>

In [21]:
sparse_matrix.toarray() # sparce 를 dense로 변환

array([[0, 1, 0, 1, 1, 1, 2, 0],
       [1, 0, 1, 0, 1, 0, 0, 1]], dtype=int64)

In [22]:
sentences

['가장 자연스럽고 좋은 ~좋은 영화 였다', '최고의 영화 4편이 기대됨']

In [23]:
from sklearn.datasets import fetch_20newsgroups #Download 진행됩니다. 

In [24]:
news =fetch_20newsgroups()

In [25]:
len(news.data), len(news.target_names)

(11314, 20)

In [30]:
news.target[2], news.target_names[2]

(4, 'comp.os.ms-windows.misc')

In [31]:
print(news.data[2])

From: twillis@ec.ecn.purdue.edu (Thomas E Willis)
Subject: PB questions...
Organization: Purdue University Engineering Computer Network
Distribution: usa
Lines: 36

well folks, my mac plus finally gave up the ghost this weekend after
starting life as a 512k way back in 1985.  sooo, i'm in the market for a
new machine a bit sooner than i intended to be...

i'm looking into picking up a powerbook 160 or maybe 180 and have a bunch
of questions that (hopefully) somebody can answer:

* does anybody know any dirt on when the next round of powerbook
introductions are expected?  i'd heard the 185c was supposed to make an
appearence "this summer" but haven't heard anymore on it - and since i
don't have access to macleak, i was wondering if anybody out there had
more info...

* has anybody heard rumors about price drops to the powerbook line like the
ones the duo's just went through recently?

* what's the impression of the display on the 180?  i could probably swing
a 180 if i got the 80Mb disk

자연어 뉴스를 배열(vector)로 변환/BOW

In [32]:
vect = CountVectorizer().fit(news.data)

In [34]:
vect.vocabulary_

{'from': 56979,
 'lerxst': 75358,
 'wam': 123162,
 'umd': 118280,
 'edu': 50527,
 'where': 124031,
 'my': 85354,
 'thing': 114688,
 'subject': 111322,
 'what': 123984,
 'car': 37780,
 'is': 68532,
 'this': 114731,
 'nntp': 87620,
 'posting': 95162,
 'host': 64095,
 'rac3': 98949,
 'organization': 90379,
 'university': 118983,
 'of': 89362,
 'maryland': 79666,
 'college': 40998,
 'park': 92081,
 'lines': 76032,
 '15': 4605,
 'was': 123292,
 'wondering': 124931,
 'if': 65798,
 'anyone': 28615,
 'out': 90774,
 'there': 114579,
 'could': 42876,
 'enlighten': 51793,
 'me': 80638,
 'on': 89860,
 'saw': 104813,
 'the': 114455,
 'other': 90686,
 'day': 45295,
 'it': 68766,
 'door': 48618,
 'sports': 109581,
 'looked': 76718,
 'to': 115475,
 'be': 32311,
 'late': 74693,
 '60s': 16574,
 'early': 50111,
 '70s': 18299,
 'called': 37433,
 'bricklin': 34995,
 'doors': 48620,
 'were': 123796,
 'really': 99822,
 'small': 108252,
 'in': 66608,
 'addition': 26073,
 'front': 56989,
 'bumper': 35612,
 'se

In [35]:
len(vect.vocabulary_)

130107

In [37]:
sm = vect.transform(news.data)

In [38]:
sm = sm.toarray()

In [119]:
from sklearn.linear_model import LogisticRegression,RidgeClassifier
import numpy as np

In [44]:
model = LogisticRegression().fit(sm, news.target)

C:\Users\wtime\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\wtime\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


In [45]:
model.score(sm,news.target)


0.999734841788934

In [53]:
test_set = ['HI, Major League, who is winner',' I want to buy a notebook.where should I go']

In [54]:
model.predict(vect.transform(test_set))

array([10,  4])

In [56]:
news.target_names[10], news.target_names[4]

('rec.sport.hockey', 'comp.sys.mac.hardware')

In [58]:
sm_test = vect.transform(test_set)
dm = sm_test[0].toarray()
dm.shape

(1, 130107)

In [62]:
np.sum(dm), dm

(6, array([[0, 0, 0, ..., 0, 0, 0]], dtype=int64))

In [63]:
sm_test[0].indices # indexes 배열의 크기가 너무 크기 때문에 0이 아닌 값이 있는 위치를 볼 수 밖에 없습니다. 

array([ 63092,  68532,  75022,  79043, 124147, 124501])

In [64]:
import konlpy

In [71]:
from konlpy.tag import Kkma, Okt
from konlpy.utils import pprint

kkma = Kkma()
pprint(kkma.sentences(u'네, 안녕하세요. 반갑습니다.'))

['네, 안녕하세요.', '반갑습니다.']


In [68]:
pprint(kkma.nouns(u'질문이나 건의사항은 깃헙 이슈 트래커에 남겨주세요.'))

['질문', '건의', '건의사항', '사항', '깃헙', '이슈', '트래커']


In [69]:
pprint(kkma.pos(u'오류보고는 실행환경, 에러메세지와함께 설명을 최대한상세히!^^'))

[('오류', 'NNG'),
 ('보고', 'NNG'),
 ('는', 'JX'),
 ('실행', 'NNG'),
 ('환경', 'NNG'),
 (',', 'SP'),
 ('에러', 'NNG'),
 ('메세지', 'NNG'),
 ('와', 'JKM'),
 ('함께', 'MAG'),
 ('설명', 'NNG'),
 ('을', 'JKO'),
 ('최대한', 'NNG'),
 ('상세히', 'MAG'),
 ('!', 'SF'),
 ('^^', 'EMO')]


In [72]:
okt_tag = Okt()
okt_tag.morphs(u'질문이나 건의사항은 깃헙 이슈 트래커에 남겨주세요.')

['질문', '이나', '건의', '사항', '은', '깃', '헙', '이슈', '트래커', '에', '남겨주세요', '.']

In [73]:
cv = CountVectorizer(tokenizer=okt_tag.morphs) # 문장 > 벡터

In [75]:
senteces = ['안녕, 나는 남자야!', '안녕, 나는 여자야 여자!']

In [80]:
cv = cv.fit(senteces) # 토큰을 다 잘라서 어휘사전(vocaburary)를 준비합니다. 

In [78]:
sparse_matrix = cv.transform(senteces) #문장을 희소 행렬로 변환


In [79]:
sparse_matrix.toarray()

array([[1, 1, 1, 1, 1, 1, 1, 0],
       [1, 1, 1, 0, 1, 1, 1, 2]], dtype=int64)

In [81]:
cv.vocabulary_

{'안녕': 5, ',': 1, '나': 2, '는': 4, '남자': 3, '야': 6, '!': 0, '여자': 7}

네이버 영화 리뷰 추천/비추천 분류

In [82]:
import pandas as pd

C:\Users\wtime\Anaconda3\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
C:\Users\wtime\Anaconda3\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


In [84]:
movie = pd.read_csv('ratings_train.txt', delimiter='\t')
movie.shape

(150000, 3)

In [85]:
movie.head()

id                                           document  label
0   9976970                                아 더빙.. 진짜 짜증나네요 목소리      0
1   3819312                  흠...포스터보고 초딩영화줄....오버연기조차 가볍지 않구나      1
2  10265843                                  너무재밓었다그래서보는것을추천한다      0
3   9045019                      교도소 이야기구먼 ..솔직히 재미는 없다..평점 조정      0
4   6483659  사이몬페그의 익살스런 연기가 돋보였던 영화!스파이더맨에서 늙어보이기만 했던 커스틴 ...      1

In [88]:
movie.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150000 entries, 0 to 149999
Data columns (total 3 columns):
id          150000 non-null int64
document    149995 non-null object
label       150000 non-null int64
dtypes: int64(2), object(1)
memory usage: 3.4+ MB


In [96]:
movie = movie.drop(columns = 'id')


KeyError: "['id'] not found in axis"

In [97]:
movie = movie.dropna()
m = 1000
movie = movie.iloc[:m]

In [98]:
movie.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1000 entries, 0 to 999
Data columns (total 2 columns):
document    1000 non-null object
label       1000 non-null int64
dtypes: int64(1), object(1)
memory usage: 23.4+ KB


In [99]:
movie.isna().sum()

document    0
label       0
dtype: int64

In [100]:
X = movie['document']
y = movie.label

In [101]:
cv = CountVectorizer(tokenizer=okt_tag.morphs) # 문장 > 벡터

In [102]:
cv.fit(X,y)

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), preprocessor=None, stop_words=None,
        strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
        tokenizer=<bound method Okt.morphs of <konlpy.tag._okt.Okt object at 0x000001E7889067F0>>,
        vocabulary=None)

In [104]:
len(cv.vocabulary_)

4767

In [105]:
X_sm = cv.transform(X)

In [106]:
X_sm

<1000x4767 sparse matrix of type '<class 'numpy.int64'>'
	with 13441 stored elements in Compressed Sparse Row format>

In [108]:
from sklearn.model_selection import cross_val_score


In [120]:
cross_val_score(RidgeClassifier(),X_sm,y,cv =3)

array([0.70658683, 0.6996997 , 0.66066066])

In [121]:
model = LogisticRegression().fit(X_sm,y)


C:\Users\wtime\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [122]:
sentence = ['두시간 동안 잘잤습니다','돈이 너무 아까워요.','너무 재밌어요','별로다','거지같어']
model.predict(cv.transform(sentence))

array([1, 0, 1, 0, 0], dtype=int64)