10개의 예상 숫자 리스트를 뽑아줘

In [17]:

import random
class Lotto:
    '''
    45개 전후의 숫자 중 6개를 맞추는 게임 : 1등 1~45의 숫자
    '''
    def __init__(self): #함수의 첫번째 인자로 self 를 넣어줍니다. JAVA의 this에 해당
        print("생성자")
        
        print("로또 정답 생성자")
        self.target = [ ]#정답 list, self를 붙이면 클래스 변수가 됩니다. 
        for i in range(5) :
            v = random.randint(1,45) #중복번호 제거 구현해야 함
            while(v in self.target) : #기존에 있는 번호면 다시 뽑아라
                v = random.randint(1,45)
            self.target.append(v)
            self.target.sort()
        print(self.target)
    
    def select(self, nums): 
        print('정답', self.target, '예측', nums)
        k=0
        for i in range(5) :
            if nums[i] in self.target:#내가 뽑은 번호가 정답이면
                k+=1#파이선은 ++,-- 증감연산자가 없다.
        if k==5 :
            print('1등 당첨되셨습니다 ')
        elif k > 1 :
            print('축하합니다. ',k,'개 맞췄습니다')
        else :
            print('땡')
        #5개의 당첨번호 1~45

In [18]:
lotto1 = Lotto();
lotto2 = Lotto()
lotto1, lotto2.select([1,2,3,4,5,6])

생성자
로또 정답 생성자
[23, 24, 26, 36, 41]
생성자
로또 정답 생성자
[2, 15, 24, 35, 42]
정답 [2, 15, 24, 35, 42] 예측 [1, 2, 3, 4, 5, 6]
땡


(<__main__.Lotto at 0x1b75dc7cac8>, None)

In [55]:
import pandas
import numpy as np
lotto_all = pandas.read_csv('lotto.csv')
lotto_all.shape
arr=numpy.array(lotto_all)
mynum=np.arange(1,46)
mynum

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45])

array([ 1.        ,  1.23609101,  1.02616461,  3.41570318,  2.87813464,
        1.01773521,  3.48109315,  3.62025029,  5.85322568,  2.72289192,
        7.78266277, 11.40307354,  4.76333349,  6.83183336,  3.17248049,
        9.1275534 , 12.05238264, 12.17326876, 16.27954129, 10.16679364,
        7.90614042, 14.82820298,  2.24876608, 20.25698491,  5.21172323,
        4.58915023, 26.40867522,  7.76695944,  4.55814704,  3.97849047,
       28.12056095,  1.13649829,  1.37459991, 13.1708306 ,  7.46416848,
       13.52686135, 21.9811167 ,  6.75625817, 18.21090257, 17.95139091,
       13.99141311, 36.77443155,  4.30533119,  6.28198578, 15.71523838])

In [52]:
np.random.uniform

array([[36, 19, 17, 24, 25]])