10개의 예상 숫자 리스트를 뽑아줘

In [17]:

import random
class Lotto:
    '''
    45개 전후의 숫자 중 6개를 맞추는 게임 : 1등 1~45의 숫자
    '''
    def __init__(self): #함수의 첫번째 인자로 self 를 넣어줍니다. JAVA의 this에 해당
        print("생성자")
        
        print("로또 정답 생성자")
        self.target = [ ]#정답 list, self를 붙이면 클래스 변수가 됩니다. 
        for i in range(5) :
            v = random.randint(1,45) #중복번호 제거 구현해야 함
            while(v in self.target) : #기존에 있는 번호면 다시 뽑아라
                v = random.randint(1,45)
            self.target.append(v)
            self.target.sort()
        print(self.target)
    
    def select(self, nums): 
        print('정답', self.target, '예측', nums)
        k=0
        for i in range(5) :
            if nums[i] in self.target:#내가 뽑은 번호가 정답이면
                k+=1#파이선은 ++,-- 증감연산자가 없다.
        if k==5 :
            print('1등 당첨되셨습니다 ')
        elif k > 1 :
            print('축하합니다. ',k,'개 맞췄습니다')
        else :
            print('땡')
        #5개의 당첨번호 1~45

In [18]:
lotto1 = Lotto();
lotto2 = Lotto()
lotto1, lotto2.select([1,2,3,4,5,6])

생성자
로또 정답 생성자
[23, 24, 26, 36, 41]
생성자
로또 정답 생성자
[2, 15, 24, 35, 42]
정답 [2, 15, 24, 35, 42] 예측 [1, 2, 3, 4, 5, 6]
땡


(<__main__.Lotto at 0x1b75dc7cac8>, None)

In [48]:
import pandas
import numpy as np
lotto_all = pandas.read_csv('lotto.csv')
lotto_num = np.array(lotto_all)
lotto_num1 = lotto_num[:,2:-1]
lotto_num1.shape, lotto_num1

((862, 6), array([[10, 34, 38, 40, 42, 43],
        [11, 17, 19, 21, 22, 25],
        [4, 8, 18, 25, 27, 32],
        ...,
        [11, 16, 19, 21, 27, 31],
        [9, 13, 21, 25, 32, 42],
        [10, 23, 29, 33, 37, 40]], dtype=object))

In [87]:
minus2= []
for i in range(5) :
    if (np.abs(lotto_num1[0,i+1] - lotto_num1[0,i])) == 2 :
        minus2.append(True)
    else : 
        minus2.append(False)
    
lotto_num1, minus2

(array([[10, 34, 38, 40, 42, 43],
        [11, 17, 19, 21, 22, 25],
        [4, 8, 18, 25, 27, 32],
        ...,
        [11, 16, 19, 21, 27, 31],
        [9, 13, 21, 25, 32, 42],
        [10, 23, 29, 33, 37, 40]], dtype=object),
 [False, False, True, True, False])

In [132]:
minus2= []
a = []
for j in range(len(lotto_num1)) :
    for i in range(5) :
        if (np.abs(lotto_num1[j,i+1] - lotto_num1[j,i])) == 2 :
            minus2.append(1)
        else : 
            minus2.append(0)
a.append(minus2)
b = np.array(a)
dif_2 = b.reshape(-1,5)
np.count_nonzero(dif_2), np.count_nonzero(dif_2, axis=1)

(array([[0, 0, 1, 1, 0],
        [0, 1, 1, 0, 0],
        [0, 0, 0, 1, 0],
        ...,
        [0, 0, 1, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]]),
 496,
 array([2, 2, 1, 1, 0, 0, 1, 2, 0, 0, 2, 0, 0, 0, 0, 2, 2, 0, 1, 1, 0, 0,
        1, 1, 1, 1, 2, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1,
        0, 0, 1, 0, 0, 1, 3, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
        0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 3, 0, 0, 0, 0, 0,
        0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 2, 1, 1, 0, 0, 1, 0, 0, 2, 2, 1, 1,
        0, 0, 0, 2, 0, 2, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0,
        0, 0, 0, 2, 1, 2, 2, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
        0, 0, 2, 0, 0, 1, 1, 2, 0, 0, 1, 0, 1, 0, 0, 0, 0, 2, 0, 2, 0, 1,
        0, 1, 1, 0, 0, 1, 0, 2, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 2, 0,
        0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 2, 0, 0, 0,
        0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
        0, 1, 0

In [135]:
minus1= []
a = []
for j in range(len(lotto_num1)) :
    for i in range(5) :
        if (np.abs(lotto_num1[j,i+1] - lotto_num1[j,i])) == 1 :
            minus1.append(1)
        else : 
            minus1.append(0)
a.append(minus1)
b = np.array(a)
dif_1 = b.reshape(-1,5)
dif_1
len(lotto_num1), np.count_nonzero(dif_1), np.count_nonzero(dif_1,axis=1)

(862,
 578,
 array([1, 1, 0, 1, 1, 0, 2, 1, 1, 1, 0, 0, 0, 0, 2, 0, 0, 0, 1, 1, 0, 0,
        1, 2, 0, 0, 0, 1, 1, 1, 1, 0, 2, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0,
        3, 1, 1, 2, 0, 1, 0, 0, 0, 0, 1, 1, 1, 2, 0, 0, 2, 1, 0, 0, 0, 1,
        1, 0, 2, 0, 0, 0, 0, 1, 1, 2, 1, 1, 1, 3, 0, 1, 0, 0, 2, 0, 1, 1,
        0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
        0, 1, 1, 0, 1, 0, 0, 2, 0, 0, 1, 1, 2, 2, 2, 0, 1, 0, 1, 1, 1, 0,
        1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 2, 0,
        0, 0, 1, 0, 0, 0, 0, 0, 2, 1, 0, 0, 0, 1, 0, 0, 1, 0, 3, 0, 2, 0,
        1, 1, 0, 1, 0, 1, 0, 0, 2, 0, 0, 0, 1, 0, 0, 1, 2, 1, 1, 1, 0, 1,
        0, 0, 1, 1, 0, 1, 0, 1, 0, 3, 0, 3, 1, 1, 1, 2, 1, 1, 0, 1, 0, 2,
        1, 1, 1, 1, 0, 1, 2, 1, 2, 1, 0, 1, 0, 1, 0, 0, 1, 2, 1, 0, 1, 1,
        1, 0, 1, 2, 0, 2, 1, 1, 1, 1, 0, 1, 1, 1, 1, 2, 1, 2, 1, 1, 0, 1,
        0, 1, 1, 0, 0, 1, 1, 2, 0, 1, 0, 1, 0, 1, 2, 0, 1, 0, 0, 0, 0, 1,
        1, 1, 2, 1, 0, 0, 

In [146]:
minus3= []
a = []
for j in range(len(lotto_num1)) :
    for i in range(5) :
        if (np.abs(lotto_num1[j,i+1] - lotto_num1[j,i])) == 3 :
            minus3.append(1)
        else : 
            minus3.append(0)
a.append(minus3)
b = np.array(a)
dif_3 = b.reshape(-1,5)
dif_3
len(lotto_num1), np.count_nonzero(dif_3), np.count_nonzero(dif_3,axis=1)

(862,
 466,
 array([0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 2, 2,
        0, 0, 2, 2, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 2, 0, 0, 0, 1, 0, 0, 0,
        1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0,
        0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0,
        2, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 2, 0, 1, 1, 0, 0, 0, 0, 0,
        1, 0, 0, 0, 1, 1, 2, 1, 2, 1, 2, 0, 0, 0, 0, 2, 1, 1, 1, 0, 0, 1,
        1, 0, 2, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 1, 0, 0, 1,
        1, 0, 0, 0, 1, 2, 2, 0, 0, 1, 0, 3, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
        1, 0, 0, 0, 1, 2, 1, 0, 0, 2, 0, 2, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
        2, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0,
        0, 1, 2, 0, 1, 0, 0, 1, 0, 1, 3, 1, 2, 1, 1, 1, 1, 1, 0, 0, 0, 1,
        0, 0, 0, 1, 0, 0, 0, 2, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 2, 1, 0,
        0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 2, 0, 0, 0, 0, 1, 0, 0, 2,
        0, 1, 1, 0, 0, 1, 

In [160]:
lotto_num1
ct_1 =0
for i in range(5) :
    if lotto_num1[0,i]<20 :
        ct_1+=1

lotto_num1[0], ct_1

(array([10, 34, 38, 40, 42, 43], dtype=object), 1)